        
#
#   This file is part of Incipio.
#
#   Incipio is an enterprise resource planning for Junior Enterprise
#   Copyright (C) 2012-2014 Florian Lefevre.
#
#   Incipio is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   Incipio is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with Incipio as the file LICENSE.  If not, see <http://www.gnu.org/licenses/>.
#

mgate_publi_publiposter:
    pattern: /Documents/Publiposter/{templateName}/{rootName}/{rootObject_id}
    defaults: {_controller: mgatePubliBundle:Traitement:publiposter}
    requirements:
        rootObject_id:  \d+
        rootName: \w+
        templateName: \w+
    
mgate_publi_telecharger:
    pattern: /publi/publiposter/telecharger
    defaults: {_controller: mgatePubliBundle:Traitement:telecharger}

mgate_publi_documenttype_upload:
    pattern: /DocumentsType/Upload
    defaults: {_controller: mgatePubliBundle:Traitement:uploadNewDoctype}  
        
        
######################
# UPLOAD DE DOCUMENT #
######################
mgate_publi_documenttype_index:
    pattern: /Documents
    defaults: {_controller: mgatePubliBundle:Document:index}

mgate_publi_document_uploadEtude:
    pattern: /Documents/Upload/Etude/{etude_id}
    defaults: {_controller: mgatePubliBundle:Document:uploadEtude}
    requirements:
        etude_id:  \d+
        
mgate_publi_document_uploadEtudiant:
    pattern: /Documents/Upload/Etudiant/{membre_id}
    defaults: {_controller: mgatePubliBundle:Document:uploadEtudiant}
    requirements:
        membre_id:  \d+

mgate_publi_document_uploadFormation:
    pattern: /Documents/Upload/Formation/{id}
    defaults: {_controller: mgatePubliBundle:Document:uploadFormation}
    requirements:
        id:  \d+
        
mgate_publi_document_uploadDoctype:
    pattern: /Documents/Upload/Doctype
    defaults: {_controller: mgatePubliBundle:Document:uploadDoctype}

mgate_publi_document_delete:
    pattern: /Documents/Supprimer/{id}
    defaults: {_controller: mgatePubliBundle:Document:delete}
    requirements:
        id:  \d+
  