        
#
#   This file is part of Incipio.
#
#   Incipio is an enterprise resource planning for Junior Enterprise
#   Copyright (C) 2012-2014 Florian Lefevre.
#
#   Incipio is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   Incipio is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with Incipio as the file LICENSE.  If not, see <http://www.gnu.org/licenses/>.
#

parameters:
    mgate.conversionlettre.class: mgate\PubliBundle\Controller\ConversionLettreController
    mgate.twigextentionmanager.class: mgate\PubliBundle\Manager\TwigExtensionManager
    mgate.documentManager.class: mgate\PubliBundle\Manager\DocumentManager


services:
    mgate.conversionlettre:
        class: "%mgate.conversionlettre.class%"
    twig.stringloader:
        class: Twig_Loader_String
        tags:
            - { name: twig.loader }
    mgate.twig_extension:
        class: "%mgate.twigextentionmanager.class%"
        tags:
            - { name: twig.extension }
    mgate.documentManager:
        class: "%mgate.documentManager.class%"
        arguments:
            em : "@doctrine.orm.entity_manager"
            container : "@service_container"
            securityContext : "@security.context"
